name: Python Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest --junitxml=result_stage1.xml
          pytest --html=report_stage1.html --self-contained-html

#    - name: Upload test report
#      uses: actions/upload-artifact@v4
#      with:
#        name: test-report
#        path: report_stage2.html

  test2:
    runs-on: ubuntu-latest
    needs: stage1  # Ensure this job runs only after stage1 finishes successfully
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest --junitxml=result_stage2.xml
          pytest --html=report_stage2.html --self-contained-html

#    - name: Upload test report
#      uses: actions/upload-artifact@v4
#      with:
#        name: test-report
#        path: report_stage2.html
